export const CANDIDATE_CSV_COLUMNS = [
  'candidate_id',
  'source_candidate_id',
  'election_year',
  'election_type',
  'election_round',
  'name',
  'ballot_name',
  'ballot_number',
  'status',
  'source_status',
  'state',
  'city',
  'party_name',
  'party_acronym',
  'party_number',
  'office_code',
  'office_name',
  'office_scope',
  'birth_date',
  'gender',
  'education',
  'occupation',
  'photo_url',
] as const;

export const CANDIDATE_ASSET_CSV_COLUMNS = [
  'asset_id',
  'candidate_id',
  'source_sequence',
  'asset_type_code',
  'asset_type',
  'description',
  'declared_value',
] as const;
